const products=[
{id:1,brand:'SONY',name:'WH-1000XM5',category:'audio',country:'🇯🇵 JAPAN',price:389000,score:4.8,reviews:1842,tags:['best'],icon:'◉',reason:'노이즈 캔슬링과 착용감의 균형이 특히 좋음',description:'주변 소음을 효과적으로 줄이면서 장시간 사용에도 편안한 무선 헤드폰. 음질, 통화, 배터리의 밸런스가 뛰어난 제품.',pros:['강력한 노이즈 캔슬링','편안한 착용감'],cons:['상위 가격대','케이스가 큰 편']},
{id:2,brand:'KEYCHRON',name:'Q1 HE',category:'tech',country:'🇺🇸 USA',price:169000,score:4.7,reviews:921,tags:['best','value'],icon:'⌨',reason:'입문부터 커스텀까지 활용도가 높은 키보드',description:'금속 하우징과 핫스왑 구조를 갖춘 커스텀 키보드. 타건감과 연결성을 원하는 사용자에게 추천.',pros:['뛰어난 타건감','커스터마이징'],cons:['무게가 있음','초보자는 설정이 필요']},
{id:3,brand:'FUJIFILM',name:'X100VI',category:'camera',country:'🇯🇵 JAPAN',price:2390000,score:4.9,reviews:632,tags:['best','new'],icon:'◎',reason:'휴대성과 사진 결과물의 만족도가 매우 높음',description:'작고 가벼운 바디에 고해상도 센서를 담은 프리미엄 컴팩트 카메라. 일상 기록과 여행에 강점.',pros:['뛰어난 화질','휴대성'],cons:['높은 가격','인기 모델로 구하기 어려움']},
{id:4,brand:'LE CREUSET',name:'Round Cocotte 24cm',category:'living',country:'🇫🇷 FRANCE',price:329000,score:4.6,reviews:418,tags:['best'],icon:'◇',reason:'오래 쓰는 주방용품을 찾는다면 만족도가 높음',description:'열 보존력이 좋은 주물 냄비. 천천히 조리하는 요리와 다양한 주방 작업에 활용하기 좋습니다.',pros:['열 보존력','내구성'],cons:['무거움','관리 필요']},
{id:5,brand:'NEW BALANCE',name:'990v6',category:'fashion',country:'🇺🇸 USA',price:219000,score:4.6,reviews:1204,tags:['value'],icon:'N',reason:'편안함과 데일리 활용성을 함께 원하는 사람에게 추천',description:'편안한 착화감과 클래식한 실루엣을 갖춘 데일리 스니커즈.',pros:['편안한 착화감','활용도 높은 디자인'],cons:['가격대','취향에 따라 투박할 수 있음']},
{id:6,brand:'APPLE',name:'AirPods Pro 3',category:'audio',country:'🇺🇸 USA',price:359000,score:4.7,reviews:2301,tags:['new'],icon:'◌',reason:'아이폰 사용자에게 편리한 연결성과 휴대성',description:'간편한 페어링과 작은 크기를 강점으로 하는 무선 이어폰. 일상용으로 접근성이 좋습니다.',pros:['편리한 연결','작은 크기'],cons:['생태계 의존도','배터리 관리 필요']},
{id:7,brand:'LOGITECH',name:'MX Master 4',category:'tech',country:'🇨🇭 SWITZERLAND',price:139000,score:4.5,reviews:788,tags:['value','new'],icon:'⌁',reason:'업무와 공부용으로 기능 대비 가격이 좋음',description:'다중 기기 연결과 다양한 단축 동작을 지원하는 생산성 중심 마우스.',pros:['생산성 기능','다중 기기'],cons:['게임용으로는 부적합','큰 편']},
{id:8,brand:'IKEA',name:'POÄNG Chair',category:'living',country:'🇸🇪 SWEDEN',price:99000,score:4.4,reviews:3441,tags:['value'],icon:'⌂',reason:'합리적인 가격으로 공간의 휴식 포인트를 만들기 좋음',description:'오래 사랑받아 온 라운지 체어. 독서나 휴식 공간에 잘 어울립니다.',pros:['합리적인 가격','편안함'],cons:['공간을 차지함','조립 필요']}
];

let activeCategory='all',activeFilter='all',query='',saved=new Set(JSON.parse(localStorage.getItem('sor-saved')||'[]'));
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const won=n=>new Intl.NumberFormat('ko-KR').format(n)+'원';
function stars(v){return '★★★★★'.split('').map((s,i)=>i<v?'★':'☆').join('')}
function filtered(){let list=products.filter(p=>(activeCategory==='all'||p.category===activeCategory)&&(activeFilter==='all'||p.tags.includes(activeFilter))&&(query===''||`${p.brand} ${p.name} ${p.country} ${p.reason}`.toLowerCase().includes(query.toLowerCase())));const sort=$('#sortSelect').value;if(sort==='rating')list.sort((a,b)=>b.score-a.score);if(sort==='price-low')list.sort((a,b)=>a.price-b.price);if(sort==='price-high')list.sort((a,b)=>b.price-a.price);return list}
function render(){const list=filtered();$('#productGrid').innerHTML=list.map(p=>`<article class="product" data-id="${p.id}"><div class="product-visual"><span class="flag">${p.country}</span><button class="save ${saved.has(p.id)?'saved':''}" data-save="${p.id}" aria-label="저장">${saved.has(p.id)?'♥':'♡'}</button><span>${p.icon}</span></div><div class="product-info"><span class="product-brand">${p.brand}</span><h3>${p.name}</h3><div class="rating"><span class="stars">${stars(p.score)}</span><b>${p.score}</b><small>(${p.reviews.toLocaleString()})</small></div><div class="price"><strong>${won(p.price)}</strong><span>예상 최저가</span></div><div class="reason"><b>추천 이유</b><br>${p.reason}</div></div></article>`).join('');$('#emptyState').hidden=list.length>0;$('#savedCount').textContent=saved.size;$$('.product').forEach(el=>el.addEventListener('click',e=>{if(e.target.closest('[data-save]'))return;openModal(Number(el.dataset.id))}));$$('[data-save]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();toggleSave(Number(b.dataset.save))}))}
function toggleSave(id){saved.has(id)?saved.delete(id):saved.add(id);localStorage.setItem('sor-saved',JSON.stringify([...saved]));render()}
function openModal(id){const p=products.find(x=>x.id===id);$('#modalContent').innerHTML=`<div class="detail"><div class="detail-art">${p.icon}</div><div><span class="product-brand">${p.brand} · ${p.country}</span><h2>${p.name}</h2><div class="big-rating"><span class="stars">${stars(p.score)}</span> <b>${p.score}</b> · ${p.reviews.toLocaleString()}개 리뷰</div><p>${p.description}</p><div class="score-box"><b>상세 평가</b><div class="score-line"><label>품질</label><div class="bar"><i style="width:${p.score*20}%"></i></div><b>${p.score.toFixed(1)}</b></div><div class="score-line"><label>가성비</label><div class="bar"><i style="width:${Math.max(70,p.score*18)}%"></i></div><b>${Math.min(5,p.score-.1).toFixed(1)}</b></div><div class="score-line"><label>추천도</label><div class="bar"><i style="width:${Math.min(100,p.score*20+2)}%"></i></div><b>${Math.min(5,p.score+.1).toFixed(1)}</b></div></div><div class="proscons"><div><b>✓ 장점</b>${p.pros.map(x=>'• '+x).join('<br>')}</div><div><b>△ 아쉬운 점</b>${p.cons.map(x=>'• '+x).join('<br>')}</div></div><div class="buy-list"><b>구매처 비교</b><div class="buy-row"><span>공식 판매처<br><small>가격 정보 연동 예정</small></span><a href="#" onclick="return false">구매처 보기</a></div><div class="buy-row"><span>글로벌 판매처<br><small>가격·배송 비교 예정</small></span><a href="#" onclick="return false">비교하기</a></div></div></div></div>`;$('#productModal').classList.add('open');$('#productModal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeModal(){$('#productModal').classList.remove('open');$('#productModal').setAttribute('aria-hidden','true');document.body.style.overflow=''}
$$('.category').forEach(b=>b.addEventListener('click',()=>{activeCategory=b.dataset.category;$$('.category').forEach(x=>x.classList.remove('active'));b.classList.add('active');render();document.querySelector('#discover').scrollIntoView({behavior:'smooth',block:'start'})}));
$$('.filter').forEach(b=>b.addEventListener('click',()=>{activeFilter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()}));
$('#searchInput').addEventListener('input',e=>{query=e.target.value.trim();render()});$('#searchBtn').addEventListener('click',()=>{$('#discover').scrollIntoView({behavior:'smooth'});render()});$('#sortSelect').addEventListener('change',render);$('#resetBtn').addEventListener('click',()=>{activeCategory='all';activeFilter='all';query='';$('#searchInput').value='';$$('.category,.filter').forEach(x=>x.classList.remove('active'));$('.category[data-category="all"]').classList.add('active');$('.filter[data-filter="all"]').classList.add('active');render()});$$('.quick-tags button').forEach(b=>b.addEventListener('click',()=>{$('#searchInput').value=b.dataset.query;query=b.dataset.query;render();$('#discover').scrollIntoView({behavior:'smooth'})}));$$('[data-close]').forEach(x=>x.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
render();