const products=[
{id:1,brand:'SONY',name:'WH-1000XM5',category:'audio',country:'🇯🇵 일본',price:389000,score:4.8,reviews:1842,tags:['best'],icon:'◉',reason:'노이즈 캔슬링·음질·착용감의 균형이 뛰어난 올라운드 헤드폰',description:'주변 소음을 효과적으로 줄이면서 장시간 사용에도 편안한 무선 헤드폰. 출퇴근, 공부, 여행처럼 오래 착용하는 상황에 특히 잘 맞습니다.',pros:['강력한 노이즈 캔슬링','편안한 착용감','긴 사용시간'],cons:['상위 가격대','케이스가 큰 편'],scores:{quality:4.9,value:4.4,design:4.8,use:4.9},sellers:[['소니 공식 스토어','공식 판매처','https://www.sony.co.kr/'],['쿠팡','국내 구매처','https://www.coupang.com/'],['Amazon','글로벌 구매처','https://www.amazon.com/']]},
{id:2,brand:'KEYCHRON',name:'Q1 HE',category:'tech',country:'🇺🇸 미국',price:169000,score:4.7,reviews:921,tags:['best','value'],icon:'⌨',reason:'입문부터 커스텀까지 활용도가 높은 키보드',description:'금속 하우징과 핫스왑 구조를 갖춘 커스텀 키보드. 타건감과 연결성을 원하는 사용자에게 추천합니다.',pros:['뛰어난 타건감','커스터마이징','무선 연결'],cons:['무게가 있음','초보자는 설정이 필요'],scores:{quality:4.8,value:4.7,design:4.6,use:4.6},sellers:[['Keychron 공식','공식 판매처','https://www.keychron.com/'],['Amazon','글로벌 구매처','https://www.amazon.com/']]},
{id:3,brand:'FUJIFILM',name:'X100VI',category:'camera',country:'🇯🇵 일본',price:2390000,score:4.9,reviews:632,tags:['best','new'],icon:'◎',reason:'휴대성과 사진 결과물의 만족도가 매우 높은 프리미엄 컴팩트 카메라',description:'작고 가벼운 바디에 고해상도 센서를 담은 프리미엄 컴팩트 카메라. 일상 기록과 여행에 강점이 있습니다.',pros:['뛰어난 화질','휴대성','필름 시뮬레이션'],cons:['높은 가격','인기 모델로 구하기 어려움'],scores:{quality:4.9,value:4.1,design:5,use:4.9},sellers:[['후지필름 공식','공식 판매처','https://fujifilm-x.com/'],['B&H Photo','글로벌 구매처','https://www.bhphotovideo.com/']]},
{id:4,brand:'LE CREUSET',name:'Round Cocotte 24cm',category:'living',country:'🇫🇷 프랑스',price:329000,score:4.6,reviews:418,tags:['best'],icon:'◇',reason:'오래 쓰는 주방용품을 찾는다면 만족도가 높은 클래식 제품',description:'열 보존력이 좋은 주물 냄비. 천천히 조리하는 요리와 다양한 주방 작업에 활용하기 좋습니다.',pros:['열 보존력','내구성','다양한 활용'],cons:['무거움','관리 필요'],scores:{quality:4.9,value:4.2,design:4.8,use:4.5},sellers:[['르크루제 공식','공식 판매처','https://www.lecreuset.com/'],['Amazon','글로벌 구매처','https://www.amazon.com/']]},
{id:5,brand:'NEW BALANCE',name:'990v6',category:'fashion',country:'🇺🇸 미국',price:219000,score:4.6,reviews:1204,tags:['value'],icon:'N',reason:'편안함과 데일리 활용성을 함께 원하는 사람에게 추천',description:'편안한 착화감과 클래식한 실루엣을 갖춘 데일리 스니커즈.',pros:['편안한 착화감','활용도 높은 디자인','안정적인 쿠셔닝'],cons:['가격대','취향에 따라 투박할 수 있음'],scores:{quality:4.7,value:4.5,design:4.6,use:4.8},sellers:[['New Balance 공식','공식 판매처','https://www.newbalance.com/'],['Amazon','글로벌 구매처','https://www.amazon.com/']]},
{id:6,brand:'APPLE',name:'AirPods Pro',category:'audio',country:'🇺🇸 미국',price:359000,score:4.7,reviews:2301,tags:['new'],icon:'◌',reason:'아이폰 사용자에게 편리한 연결성과 휴대성이 강점',description:'간편한 페어링과 작은 크기를 강점으로 하는 무선 이어폰. 일상용으로 접근성이 좋습니다.',pros:['편리한 연결','작은 크기','휴대성'],cons:['생태계 의존도','배터리 관리 필요'],scores:{quality:4.7,value:4.4,design:4.8,use:4.9},sellers:[['Apple 공식','공식 판매처','https://www.apple.com/kr/'],['쿠팡','국내 구매처','https://www.coupang.com/']]},
{id:7,brand:'LOGITECH',name:'MX Master',category:'tech',country:'🇨🇭 스위스',price:139000,score:4.5,reviews:788,tags:['value','new'],icon:'⌁',reason:'업무와 공부용으로 기능 대비 만족도가 높은 생산성 마우스',description:'다중 기기 연결과 다양한 단축 동작을 지원하는 생산성 중심 마우스.',pros:['생산성 기능','다중 기기','편안한 그립'],cons:['게임용으로는 부적합','큰 편'],scores:{quality:4.6,value:4.6,design:4.4,use:4.8},sellers:[['Logitech 공식','공식 판매처','https://www.logitech.com/'],['Amazon','글로벌 구매처','https://www.amazon.com/']]},
{id:8,brand:'IKEA',name:'POÄNG Chair',category:'living',country:'🇸🇪 스웨덴',price:99000,score:4.4,reviews:3441,tags:['value'],icon:'⌂',reason:'합리적인 가격으로 공간에 편안한 휴식 포인트를 만들기 좋음',description:'오래 사랑받아 온 라운지 체어. 독서나 휴식 공간에 잘 어울립니다.',pros:['합리적인 가격','편안함','부품 교체 가능'],cons:['공간을 차지함','조립 필요'],scores:{quality:4.4,value:4.8,design:4.5,use:4.6},sellers:[['IKEA 공식','공식 판매처','https://www.ikea.com/kr/']]},
{id:9,brand:'DYSON',name:'Airwrap',category:'living',country:'🇬🇧 영국',price:699000,score:4.5,reviews:5170,tags:['best'],icon:'✦',reason:'여러 스타일링을 하나의 기기로 해결하고 싶은 사람에게 추천',description:'다양한 스타일링 헤드와 공기 흐름을 활용하는 프리미엄 헤어 스타일러.',pros:['다양한 스타일링','완성도 높은 구성','프리미엄 디자인'],cons:['높은 가격','구성품이 많음'],scores:{quality:4.7,value:4.0,design:4.9,use:4.6},sellers:[['Dyson 공식','공식 판매처','https://www.dyson.co.kr/'],['Amazon','글로벌 구매처','https://www.amazon.com/']]},
{id:10,brand:'KODAK',name:'PIXPRO FZ55',category:'camera',country:'🇺🇸 미국',price:179000,score:4.2,reviews:486,tags:['value'],icon:'▣',reason:'가볍게 들고 다니며 간단한 사진을 즐기기 좋은 입문용 카메라',description:'작은 바디와 간단한 조작으로 일상 스냅을 즐기기 좋은 컴팩트 카메라.',pros:['작고 가벼움','간단한 조작','부담 낮은 가격'],cons:['고급 기능 제한','저조도 한계'],scores:{quality:4.0,value:4.7,design:4.4,use:4.5},sellers:[['Kodak 공식','공식 판매처','https://kodakpixpro.com/'],['Amazon','글로벌 구매처','https://www.amazon.com/']]},
{id:11,brand:'HARIO',name:'V60 Drip Kettle',category:'living',country:'🇯🇵 일본',price:89000,score:4.5,reviews:1108,tags:['value','new'],icon:'☕',reason:'커피를 직접 내려 마시는 사람에게 정교한 물줄기 제어를 제공',description:'핸드드립을 위한 세밀한 물줄기 제어에 초점을 둔 주전자.',pros:['정교한 추출 제어','깔끔한 디자인','관리 쉬움'],cons:['용량이 작음','커피 외 활용도 낮음'],scores:{quality:4.5,value:4.7,design:4.5,use:4.6},sellers:[['HARIO 공식','공식 판매처','https://global.hario.com/'],['Amazon','글로벌 구매처','https://www.amazon.com/']]},
{id:12,brand:'MUJI',name:'Travel Organizer',category:'fashion',country:'🇯🇵 일본',price:39000,score:4.3,reviews:2032,tags:['value','new'],icon:'▤',reason:'여행 짐을 깔끔하게 나누고 싶은 사람에게 부담 없는 선택',description:'작은 물건과 여행용품을 나눠 담기 좋은 심플한 수납 파우치.',pros:['가벼움','수납 편의성','심플한 디자인'],cons:['대형 물품에는 부적합','소재 취향 차이'],scores:{quality:4.2,value:4.6,design:4.4,use:4.5},sellers:[['MUJI 공식','공식 판매처','https://www.muji.com/'],['Amazon','글로벌 구매처','https://www.amazon.com/']]}
];

let activeCategory='all',activeFilter='all',query='',saved=new Set(JSON.parse(localStorage.getItem('sor-saved')||'[]'));
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const won=n=>new Intl.NumberFormat('ko-KR').format(n)+'원';
const stars=v=>'★★★★★'.split('').map((s,i)=>i<v?'★':'☆').join('');
function filtered(){let list=products.filter(p=>(activeCategory==='all'||p.category===activeCategory)&&(activeFilter==='all'||p.tags.includes(activeFilter))&&(query===''||`${p.brand} ${p.name} ${p.country} ${p.reason} ${p.description}`.toLowerCase().includes(query.toLowerCase())));const sort=$('#sortSelect').value;if(sort==='rating')list.sort((a,b)=>b.score-a.score);if(sort==='price-low')list.sort((a,b)=>a.price-b.price);if(sort==='price-high')list.sort((a,b)=>b.price-a.price);return list}
function render(){const list=filtered();$('#productGrid').innerHTML=list.map(p=>`<article class="product" data-id="${p.id}"><div class="product-visual product-${p.category}"><span class="flag">${p.country}</span><button class="save ${saved.has(p.id)?'saved':''}" data-save="${p.id}" aria-label="저장">${saved.has(p.id)?'♥':'♡'}</button><span>${p.icon}</span><small>CURATED</small></div><div class="product-info"><span class="product-brand">${p.brand}</span><h3>${p.name}</h3><div class="rating"><span class="stars">${stars(p.score)}</span><b>${p.score}</b><small>(${p.reviews.toLocaleString()})</small></div><div class="price"><strong>${won(p.price)}</strong><span>데모 기준가</span></div><div class="reason"><b>추천 이유</b><br>${p.reason}</div></div></article>`).join('');$('#emptyState').hidden=list.length>0;$('#resultCount').textContent=`${list.length}개 상품`;$('#savedCount').textContent=saved.size;$$('.product').forEach(el=>el.addEventListener('click',e=>{if(e.target.closest('[data-save]'))return;openModal(Number(el.dataset.id))}));$$('[data-save]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();toggleSave(Number(b.dataset.save))}))}
function toggleSave(id){saved.has(id)?saved.delete(id):saved.add(id);localStorage.setItem('sor-saved',JSON.stringify([...saved]));render()}
function openModal(id){const p=products.find(x=>x.id===id);const scoreRows=Object.entries({품질:p.scores.quality,가성비:p.scores.value,디자인:p.scores.design,사용성:p.scores.use}).map(([label,value])=>`<div class="score-line"><label>${label}</label><div class="bar"><i style="width:${value*20}%"></i></div><b>${value.toFixed(1)}</b></div>`).join('');const sellers=p.sellers.map(([name,type,url])=>`<div class="buy-row"><span><b>${name}</b><small>${type}</small></span><a href="${url}" target="_blank" rel="noopener">사이트 보기 ↗</a></div>`).join('');$('#modalContent').innerHTML=`<div class="detail"><div class="detail-art product-${p.category}"><span>${p.icon}</span></div><div><span class="product-brand">${p.brand} · ${p.country}</span><h2>${p.name}</h2><div class="big-rating"><span class="stars">${stars(p.score)}</span> <b>${p.score}</b> · ${p.reviews.toLocaleString()}개 평가</div><p>${p.description}</p><div class="recommend-banner"><b>이런 사람에게 추천</b><span>${p.reason}</span></div><div class="score-box"><b>상세 평가</b>${scoreRows}</div><div class="proscons"><div><b>✓ 장점</b>${p.pros.map(x=>'• '+x).join('<br>')}</div><div><b>△ 아쉬운 점</b>${p.cons.map(x=>'• '+x).join('<br>')}</div></div><div class="review-box"><b>에디터 리뷰</b><p>이 상품은 단순 평점보다 <strong>${p.scores.value>=4.6?'가격 대비 만족도':'제품 완성도'}</strong>를 중요하게 보는 사람에게 좋은 후보입니다. 구매 전에는 판매처별 가격, 배송비, 재고를 확인하는 것을 추천합니다.</p></div><div class="buy-list"><b>구매처</b><small class="demo-note">※ 현재는 공식 사이트 연결이 포함된 데모 데이터입니다. 실시간 가격·재고 API는 다음 단계에서 연결할 수 있습니다.</small>${sellers}</div></div></div>`;$('#productModal').classList.add('open');$('#productModal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeModal(){$('#productModal').classList.remove('open');$('#productModal').setAttribute('aria-hidden','true');document.body.style.overflow=''}
$$('.category').forEach(b=>b.addEventListener('click',()=>{activeCategory=b.dataset.category;$$('.category').forEach(x=>x.classList.remove('active'));b.classList.add('active');render();document.querySelector('#discover').scrollIntoView({behavior:'smooth',block:'start'})}));
$$('.filter').forEach(b=>b.addEventListener('click',()=>{activeFilter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()}));
$('#searchInput').addEventListener('input',e=>{query=e.target.value.trim();render()});$('#searchBtn').addEventListener('click',()=>{$('#discover').scrollIntoView({behavior:'smooth'});render()});$('#sortSelect').addEventListener('change',render);$('#resetBtn').addEventListener('click',()=>{activeCategory='all';activeFilter='all';query='';$('#searchInput').value='';$$('.category,.filter').forEach(x=>x.classList.remove('active'));$('.category[data-category="all"]').classList.add('active');$('.filter[data-filter="all"]').classList.add('active');render()});$$('.quick-tags button').forEach(b=>b.addEventListener('click',()=>{$('#searchInput').value=b.dataset.query;query=b.dataset.query;render();$('#discover').scrollIntoView({behavior:'smooth'})}));$('#savedBtn').addEventListener('click',()=>{activeCategory='all';activeFilter='all';query='';$('#searchInput').value='';render();document.querySelector('#discover').scrollIntoView({behavior:'smooth'});if(saved.size)alert(`저장한 상품 ${saved.size}개가 표시됩니다. 저장된 상품만 보기 기능은 다음 UI 단계에서 확장할 수 있습니다.`)});$$('[data-close]').forEach(x=>x.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});

// Product structured data: enables search engines to understand product, rating and offer information.
function injectSchema(p){let old=$('#product-schema');if(old)old.remove();const script=document.createElement('script');script.id='product-schema';script.type='application/ld+json';script.textContent=JSON.stringify({'@context':'https://schema.org','@type':'Product',name:`${p.brand} ${p.name}`,description:p.description,brand:{'@type':'Brand',name:p.brand},aggregateRating:{'@type':'AggregateRating',ratingValue:p.score,bestRating:5,ratingCount:p.reviews},offers:{'@type':'Offer',price:p.price,priceCurrency:'KRW',availability:'https://schema.org/InStock'}});document.head.appendChild(script)}
const originalOpen=openModal;openModal=id=>{const p=products.find(x=>x.id===id);injectSchema(p);originalOpen(id)};
render();